# Generated by Django 4.2.1 on 2023-05-23 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.IntegerField(primary_key=True, serialize=False)),
                ('Photo', models.ImageField(upload_to='books/')),
                ('Titre', models.CharField(max_length=20)),
                ('Edition', models.CharField(max_length=20)),
                ('Desc', models.CharField(max_length=500)),
                ('Prix_vente', models.FloatField()),
                ('Prix_empr', models.FloatField()),
                ('Audio', models.FileField(upload_to='')),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_book.auteur')),
                ('Categorie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion_book.categorie')),
            ],
        ),
    ]
